/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'twcn' at '3/2/16 10:08 PM' with Gradle 2.11
 *
 * @author twcn, @date 3/2/16 10:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
